// Typed client for the drain-cover Anchor program: PDA derivation, account
// decoding, instruction builders. The IDL is generated by `anchor build` into
// target/idl and copied here — it is a build artifact, not hand-written.
export {}
