// Typed client for the drain-cover Anchor program: PDA derivation, account
// decoding, instruction builders. The IDL is generated by `anchor build` into
// target/ and synced here by `pnpm --filter @mandate/sdk sync:idl` — it is a
// build artifact, not hand-written.
import { type AnchorProvider, Program } from '@coral-xyz/anchor'
import { PublicKey } from '@solana/web3.js'
import { DRAIN_COVER_IDL, type DrainCover, PROGRAM_ID_FROM_IDL } from './idl'

export * from './idl'
export * from './pdas'

export const PROGRAM_ID = new PublicKey(PROGRAM_ID_FROM_IDL)

/**
 * The program client. The id comes from the IDL rather than from an argument or an
 * environment variable: a client pointed at an address the program was not built
 * for fails in ways that look like logic bugs, and `.env.example`, `Anchor.toml`
 * and `declare_id!` are already cross-checked against each other.
 */
export const createProgram = (provider: AnchorProvider): Program<DrainCover> =>
  new Program(DRAIN_COVER_IDL, provider)
