[toolchain]
anchor_version = "0.32.1"
solana_version = "4.2.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
drain_cover = "DsRdHv4QRYQ7teVhwuLVttktF792gvDFQdiuraQ4eF4P"

[programs.localnet]
drain_cover = "DsRdHv4QRYQ7teVhwuLVttktF792gvDFQdiuraQ4eF4P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm vitest run --dir tests"
